services:
  sio_test:
    user: app
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    ports:
      - "8337:8337"
    volumes:
      - .:/app:rw
    environment:
      - APP_ENV=dev
      - APP_SECRET=6841bd5feebc61e4f9f4f6e6eb1f44ee
      - DATABASE_URL=mysql://root:digitmindreason@database:3306/purchases?serverVersion=8.0&charset=utf8mb4
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: purchases
      MYSQL_ROOT_PASSWORD: digitmindreason
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    #volumes:
    #  - database_data:/var/lib/mysql:rw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdigitmindreason" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  database_data: